/** Contract: contracts/notifications/rules.md */
import type { EventBusModule, DomainEvent } from '../../events/contract.ts';
import type { NotificationStore, NotificationType } from '../contract.ts';
import { createLogger } from '../../logger/index.ts';

const log = createLogger('notifications');

/** Map EventBus event types to notification types. */
const EVENT_TO_NOTIFICATION: Record<string, NotificationType> = {
  GrantCreated: 'document_shared',
  WorkflowTriggered: 'workflow_triggered',
};

/**
 * Subscribe to EventBus events and create notifications.
 * Comment and KB notifications require additional context
 * that the thin DomainEvent does not carry, so those are
 * generated by their respective API routes directly.
 */
export async function subscribeNotifications(
  eventBus: EventBusModule,
  store: NotificationStore,
): Promise<void> {
  const eventTypes = Object.keys(EVENT_TO_NOTIFICATION);

  await eventBus.subscribe(
    'notification-generator',
    eventTypes as never[],
    async (event: DomainEvent) => {
      const notifType = EVENT_TO_NOTIFICATION[event.type];
      if (!notifType) return;

      try {
        await store.create({
          user_id: event.actorId,
          type: notifType,
          payload: {
            eventId: event.id,
            aggregateId: event.aggregateId,
            eventType: event.type,
            occurredAt: event.occurredAt,
          },
        });
      } catch (err) {
        log.error('failed to create notification from event', {
          eventId: event.id,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    },
  );
}
