/** Contract: contracts/app/rules.md */
import type { EmojiEntry } from './emoji-data.ts';

/** Activities, Travel, Objects, Symbols emojis. */
export const EMOJIS_PART_2: EmojiEntry[] = [
  // Activities
  { emoji: '\u26BD', name: 'soccer', category: 'activities', keywords: ['football', 'sport', 'ball'] },
  { emoji: '\u{1F3C0}', name: 'basketball', category: 'activities', keywords: ['sport', 'ball', 'hoop'] },
  { emoji: '\u{1F3C8}', name: 'football', category: 'activities', keywords: ['american', 'sport', 'ball'] },
  { emoji: '\u26BE', name: 'baseball', category: 'activities', keywords: ['sport', 'ball'] },
  { emoji: '\u{1F3BE}', name: 'tennis', category: 'activities', keywords: ['sport', 'racket'] },
  { emoji: '\u{1F3B5}', name: 'music', category: 'activities', keywords: ['note', 'sound', 'song'] },
  { emoji: '\u{1F3B6}', name: 'notes', category: 'activities', keywords: ['music', 'sound', 'melody'] },
  { emoji: '\u{1F3A8}', name: 'art', category: 'activities', keywords: ['paint', 'palette', 'creative'] },
  { emoji: '\u{1F3AE}', name: 'video_game', category: 'activities', keywords: ['controller', 'gaming'] },
  { emoji: '\u{1F3AF}', name: 'dart', category: 'activities', keywords: ['target', 'bullseye'] },
  { emoji: '\u{1F3C6}', name: 'trophy', category: 'activities', keywords: ['win', 'prize', 'award'] },
  { emoji: '\u{1F3C5}', name: 'medal', category: 'activities', keywords: ['win', 'sports', 'award'] },
  { emoji: '\u{1F396}\uFE0F', name: 'military_medal', category: 'activities', keywords: ['honor', 'award'] },
  { emoji: '\u{1F3AD}', name: 'theater', category: 'activities', keywords: ['drama', 'masks', 'acting'] },
  { emoji: '\u{1F3A4}', name: 'microphone', category: 'activities', keywords: ['sing', 'karaoke'] },

  // Travel
  { emoji: '\u{1F697}', name: 'car', category: 'travel', keywords: ['automobile', 'drive'] },
  { emoji: '\u{1F68C}', name: 'bus', category: 'travel', keywords: ['transport', 'public'] },
  { emoji: '\u{1F682}', name: 'train', category: 'travel', keywords: ['transport', 'rail'] },
  { emoji: '\u2708\uFE0F', name: 'airplane', category: 'travel', keywords: ['fly', 'flight', 'travel'] },
  { emoji: '\u{1F680}', name: 'rocket', category: 'travel', keywords: ['space', 'launch', 'fast'] },
  { emoji: '\u{1F30D}', name: 'earth_africa', category: 'travel', keywords: ['world', 'globe', 'planet'] },
  { emoji: '\u{1F30E}', name: 'earth_americas', category: 'travel', keywords: ['world', 'globe'] },
  { emoji: '\u{1F30F}', name: 'earth_asia', category: 'travel', keywords: ['world', 'globe'] },
  { emoji: '\u{1F3D6}\uFE0F', name: 'beach', category: 'travel', keywords: ['vacation', 'sun', 'sand'] },
  { emoji: '\u{1F3D4}\uFE0F', name: 'mountain', category: 'travel', keywords: ['nature', 'snow'] },
  { emoji: '\u{1F3E0}', name: 'house', category: 'travel', keywords: ['home', 'building'] },
  { emoji: '\u{1F3E2}', name: 'office', category: 'travel', keywords: ['building', 'work'] },
  { emoji: '\u{1F3EB}', name: 'school', category: 'travel', keywords: ['education', 'building'] },
  { emoji: '\u{1F5FF}', name: 'moai', category: 'travel', keywords: ['statue', 'easter_island'] },

  // Objects
  { emoji: '\u{1F4A1}', name: 'bulb', category: 'objects', keywords: ['idea', 'light'] },
  { emoji: '\u{1F4BB}', name: 'computer', category: 'objects', keywords: ['laptop', 'tech'] },
  { emoji: '\u{1F4F1}', name: 'phone', category: 'objects', keywords: ['mobile', 'cell', 'call'] },
  { emoji: '\u{1F4E7}', name: 'email', category: 'objects', keywords: ['mail', 'letter', 'envelope'] },
  { emoji: '\u{1F4DA}', name: 'books', category: 'objects', keywords: ['read', 'study', 'library'] },
  { emoji: '\u{1F4DD}', name: 'memo', category: 'objects', keywords: ['note', 'write', 'pencil'] },
  { emoji: '\u270F\uFE0F', name: 'pencil', category: 'objects', keywords: ['write', 'draw', 'edit'] },
  { emoji: '\u{1F4CE}', name: 'paperclip', category: 'objects', keywords: ['attach', 'clip'] },
  { emoji: '\u{1F512}', name: 'lock', category: 'objects', keywords: ['secure', 'private', 'closed'] },
  { emoji: '\u{1F513}', name: 'unlock', category: 'objects', keywords: ['open', 'access'] },
  { emoji: '\u{1F511}', name: 'key', category: 'objects', keywords: ['password', 'access', 'lock'] },
  { emoji: '\u{1F50D}', name: 'search', category: 'objects', keywords: ['magnify', 'find', 'look'] },
  { emoji: '\u{1F4CA}', name: 'chart', category: 'objects', keywords: ['graph', 'data', 'stats'] },
  { emoji: '\u{1F4C5}', name: 'calendar', category: 'objects', keywords: ['date', 'schedule'] },
  { emoji: '\u{1F4CB}', name: 'clipboard', category: 'objects', keywords: ['list', 'paste'] },
  { emoji: '\u{1F4CC}', name: 'pushpin', category: 'objects', keywords: ['pin', 'location'] },
  { emoji: '\u23F0', name: 'alarm_clock', category: 'objects', keywords: ['time', 'wake', 'timer'] },
  { emoji: '\u{1F4B0}', name: 'money_bag', category: 'objects', keywords: ['dollar', 'rich', 'cash'] },
  { emoji: '\u{1F381}', name: 'gift', category: 'objects', keywords: ['present', 'birthday', 'wrapped'] },
  { emoji: '\u{1F3F7}\uFE0F', name: 'label', category: 'objects', keywords: ['tag', 'price'] },

  // Symbols
  { emoji: '\u2764\uFE0F', name: 'heart', category: 'symbols', keywords: ['love', 'red'] },
  { emoji: '\u{1F9E1}', name: 'orange_heart', category: 'symbols', keywords: ['love'] },
  { emoji: '\u{1F49B}', name: 'yellow_heart', category: 'symbols', keywords: ['love'] },
  { emoji: '\u{1F49A}', name: 'green_heart', category: 'symbols', keywords: ['love'] },
  { emoji: '\u{1F499}', name: 'blue_heart', category: 'symbols', keywords: ['love'] },
  { emoji: '\u{1F49C}', name: 'purple_heart', category: 'symbols', keywords: ['love'] },
  { emoji: '\u2705', name: 'check', category: 'symbols', keywords: ['yes', 'done', 'complete', 'tick'] },
  { emoji: '\u274C', name: 'x', category: 'symbols', keywords: ['no', 'wrong', 'cross', 'delete'] },
  { emoji: '\u2B50', name: 'star', category: 'symbols', keywords: ['favorite', 'gold', 'rating'] },
  { emoji: '\u{1F31F}', name: 'star2', category: 'symbols', keywords: ['glowing', 'sparkle'] },
  { emoji: '\u{1F525}', name: 'fire', category: 'symbols', keywords: ['hot', 'flame', 'lit'] },
  { emoji: '\u{1F4A5}', name: 'boom', category: 'symbols', keywords: ['explosion', 'crash', 'bang'] },
  { emoji: '\u{1F4AF}', name: 'hundred', category: 'symbols', keywords: ['perfect', 'score', '100'] },
  { emoji: '\u26A0\uFE0F', name: 'warning', category: 'symbols', keywords: ['caution', 'alert'] },
  { emoji: '\u{1F6AB}', name: 'no_entry', category: 'symbols', keywords: ['forbidden', 'stop'] },
  { emoji: '\u2753', name: 'question', category: 'symbols', keywords: ['ask', 'help', 'what'] },
  { emoji: '\u2757', name: 'exclamation', category: 'symbols', keywords: ['important', 'alert', 'bang'] },
  { emoji: '\u{1F4AC}', name: 'speech', category: 'symbols', keywords: ['chat', 'talk', 'bubble'] },
  { emoji: '\u{1F4AD}', name: 'thought', category: 'symbols', keywords: ['think', 'bubble'] },
  { emoji: '\u267B\uFE0F', name: 'recycle', category: 'symbols', keywords: ['green', 'eco'] },
  { emoji: '\u{1F389}', name: 'tada', category: 'symbols', keywords: ['party', 'celebrate', 'congrats'] },
  { emoji: '\u{1F38A}', name: 'confetti', category: 'symbols', keywords: ['party', 'celebrate'] },
  { emoji: '\u{1F48E}', name: 'gem', category: 'symbols', keywords: ['diamond', 'jewel'] },
  { emoji: '\u{1F3B2}', name: 'dice', category: 'symbols', keywords: ['game', 'random', 'chance'] },
];
