/** Contract: contracts/app/rules.md */
import type { EmojiEntry } from './emoji-data.ts';

/** Smileys, People, Animals, Food emojis. */
export const EMOJIS_PART_1: EmojiEntry[] = [
  // Smileys
  { emoji: '\u{1F600}', name: 'grinning', category: 'smileys', keywords: ['happy', 'smile', 'face'] },
  { emoji: '\u{1F603}', name: 'smiley', category: 'smileys', keywords: ['happy', 'face', 'smile'] },
  { emoji: '\u{1F604}', name: 'smile', category: 'smileys', keywords: ['happy', 'joy', 'face'] },
  { emoji: '\u{1F601}', name: 'grin', category: 'smileys', keywords: ['happy', 'face'] },
  { emoji: '\u{1F606}', name: 'laughing', category: 'smileys', keywords: ['happy', 'lol', 'haha'] },
  { emoji: '\u{1F605}', name: 'sweat_smile', category: 'smileys', keywords: ['hot', 'relief'] },
  { emoji: '\u{1F923}', name: 'rofl', category: 'smileys', keywords: ['lol', 'laugh', 'rolling'] },
  { emoji: '\u{1F602}', name: 'joy', category: 'smileys', keywords: ['tears', 'laugh', 'cry'] },
  { emoji: '\u{1F642}', name: 'slightly_smiling', category: 'smileys', keywords: ['smile', 'face'] },
  { emoji: '\u{1F643}', name: 'upside_down', category: 'smileys', keywords: ['silly', 'sarcasm'] },
  { emoji: '\u{1F609}', name: 'wink', category: 'smileys', keywords: ['flirt', 'face'] },
  { emoji: '\u{1F60A}', name: 'blush', category: 'smileys', keywords: ['shy', 'happy', 'face'] },
  { emoji: '\u{1F607}', name: 'innocent', category: 'smileys', keywords: ['angel', 'halo'] },
  { emoji: '\u{1F60D}', name: 'heart_eyes', category: 'smileys', keywords: ['love', 'crush', 'face'] },
  { emoji: '\u{1F618}', name: 'kissing_heart', category: 'smileys', keywords: ['love', 'kiss'] },
  { emoji: '\u{1F61C}', name: 'stuck_out_tongue_winking', category: 'smileys', keywords: ['playful', 'joke'] },
  { emoji: '\u{1F914}', name: 'thinking', category: 'smileys', keywords: ['hmm', 'wonder'] },
  { emoji: '\u{1F928}', name: 'raised_eyebrow', category: 'smileys', keywords: ['skeptical', 'doubt'] },
  { emoji: '\u{1F610}', name: 'neutral', category: 'smileys', keywords: ['meh', 'blank', 'face'] },
  { emoji: '\u{1F611}', name: 'expressionless', category: 'smileys', keywords: ['blank', 'face'] },
  { emoji: '\u{1F636}', name: 'no_mouth', category: 'smileys', keywords: ['silent', 'quiet'] },
  { emoji: '\u{1F60F}', name: 'smirk', category: 'smileys', keywords: ['smug', 'flirt'] },
  { emoji: '\u{1F612}', name: 'unamused', category: 'smileys', keywords: ['annoyed', 'bored'] },
  { emoji: '\u{1F644}', name: 'eye_roll', category: 'smileys', keywords: ['whatever', 'annoyed'] },
  { emoji: '\u{1F62C}', name: 'grimacing', category: 'smileys', keywords: ['awkward', 'nervous'] },
  { emoji: '\u{1F62E}\u200D\u{1F4A8}', name: 'exhale', category: 'smileys', keywords: ['sigh', 'relief', 'breath'] },
  { emoji: '\u{1F625}', name: 'relieved_sad', category: 'smileys', keywords: ['sad', 'disappointed'] },
  { emoji: '\u{1F622}', name: 'cry', category: 'smileys', keywords: ['sad', 'tears', 'upset'] },
  { emoji: '\u{1F62D}', name: 'sob', category: 'smileys', keywords: ['cry', 'sad', 'tears'] },
  { emoji: '\u{1F631}', name: 'scream', category: 'smileys', keywords: ['horror', 'scared', 'shocked'] },
  { emoji: '\u{1F621}', name: 'rage', category: 'smileys', keywords: ['angry', 'mad'] },
  { emoji: '\u{1F624}', name: 'triumph', category: 'smileys', keywords: ['steam', 'proud', 'huff'] },
  { emoji: '\u{1F971}', name: 'yawning', category: 'smileys', keywords: ['bored', 'tired', 'sleepy'] },
  { emoji: '\u{1F634}', name: 'sleeping', category: 'smileys', keywords: ['zzz', 'tired', 'sleep'] },
  { emoji: '\u{1F92F}', name: 'exploding_head', category: 'smileys', keywords: ['mind_blown', 'shocked'] },
  { emoji: '\u{1F920}', name: 'cowboy', category: 'smileys', keywords: ['hat', 'western'] },
  { emoji: '\u{1F973}', name: 'partying', category: 'smileys', keywords: ['celebration', 'party', 'hat'] },
  { emoji: '\u{1F60E}', name: 'sunglasses', category: 'smileys', keywords: ['cool', 'face'] },
  { emoji: '\u{1F913}', name: 'nerd', category: 'smileys', keywords: ['glasses', 'geek'] },
  { emoji: '\u{1F974}', name: 'woozy', category: 'smileys', keywords: ['dizzy', 'drunk'] },

  // People
  { emoji: '\u{1F44D}', name: 'thumbsup', category: 'people', keywords: ['yes', 'ok', 'like', 'approve'] },
  { emoji: '\u{1F44E}', name: 'thumbsdown', category: 'people', keywords: ['no', 'dislike', 'reject'] },
  { emoji: '\u{1F44F}', name: 'clap', category: 'people', keywords: ['applause', 'bravo'] },
  { emoji: '\u{1F64F}', name: 'pray', category: 'people', keywords: ['please', 'thanks', 'hope'] },
  { emoji: '\u{1F4AA}', name: 'muscle', category: 'people', keywords: ['strong', 'flex', 'bicep'] },
  { emoji: '\u{1F44B}', name: 'wave', category: 'people', keywords: ['hello', 'goodbye', 'hi'] },
  { emoji: '\u270C\uFE0F', name: 'victory', category: 'people', keywords: ['peace', 'two'] },
  { emoji: '\u{1F91D}', name: 'handshake', category: 'people', keywords: ['deal', 'agree'] },
  { emoji: '\u{1F91E}', name: 'crossed_fingers', category: 'people', keywords: ['luck', 'hope'] },
  { emoji: '\u261D\uFE0F', name: 'point_up', category: 'people', keywords: ['index', 'finger'] },
  { emoji: '\u{1F44C}', name: 'ok_hand', category: 'people', keywords: ['perfect', 'fine'] },
  { emoji: '\u{1F918}', name: 'rock', category: 'people', keywords: ['metal', 'horns'] },
  { emoji: '\u{1F44A}', name: 'fist', category: 'people', keywords: ['punch', 'bump'] },
  { emoji: '\u{1F91F}', name: 'love_you', category: 'people', keywords: ['hand', 'ily'] },
  { emoji: '\u{1F3C3}', name: 'runner', category: 'people', keywords: ['run', 'jog', 'exercise'] },
  { emoji: '\u{1F926}', name: 'facepalm', category: 'people', keywords: ['smh', 'frustration'] },
  { emoji: '\u{1F937}', name: 'shrug', category: 'people', keywords: ['idk', 'whatever'] },
  { emoji: '\u{1F646}', name: 'ok_person', category: 'people', keywords: ['yes', 'gesture'] },
  { emoji: '\u{1F645}', name: 'no_good', category: 'people', keywords: ['no', 'stop', 'gesture'] },
  { emoji: '\u{1F64B}', name: 'raising_hand', category: 'people', keywords: ['question', 'volunteer'] },

  // Animals
  { emoji: '\u{1F436}', name: 'dog', category: 'animals', keywords: ['puppy', 'pet', 'woof'] },
  { emoji: '\u{1F431}', name: 'cat', category: 'animals', keywords: ['kitten', 'pet', 'meow'] },
  { emoji: '\u{1F42D}', name: 'mouse', category: 'animals', keywords: ['rodent', 'small'] },
  { emoji: '\u{1F439}', name: 'hamster', category: 'animals', keywords: ['pet', 'cute'] },
  { emoji: '\u{1F430}', name: 'rabbit', category: 'animals', keywords: ['bunny', 'easter'] },
  { emoji: '\u{1F43B}', name: 'bear', category: 'animals', keywords: ['grizzly', 'animal'] },
  { emoji: '\u{1F43C}', name: 'panda', category: 'animals', keywords: ['bear', 'bamboo'] },
  { emoji: '\u{1F428}', name: 'koala', category: 'animals', keywords: ['australia', 'cute'] },
  { emoji: '\u{1F981}', name: 'lion', category: 'animals', keywords: ['king', 'jungle', 'cat'] },
  { emoji: '\u{1F984}', name: 'unicorn', category: 'animals', keywords: ['magic', 'fantasy', 'horse'] },
  { emoji: '\u{1F422}', name: 'turtle', category: 'animals', keywords: ['slow', 'shell'] },
  { emoji: '\u{1F40D}', name: 'snake', category: 'animals', keywords: ['reptile', 'hiss'] },
  { emoji: '\u{1F433}', name: 'whale', category: 'animals', keywords: ['ocean', 'sea'] },
  { emoji: '\u{1F427}', name: 'penguin', category: 'animals', keywords: ['ice', 'bird', 'cold'] },
  { emoji: '\u{1F426}', name: 'bird', category: 'animals', keywords: ['tweet', 'fly'] },
  { emoji: '\u{1F98B}', name: 'butterfly', category: 'animals', keywords: ['insect', 'pretty'] },
  { emoji: '\u{1F41D}', name: 'bee', category: 'animals', keywords: ['honey', 'buzz', 'insect'] },
  { emoji: '\u{1F419}', name: 'octopus', category: 'animals', keywords: ['tentacles', 'ocean'] },

  // Food
  { emoji: '\u{1F34E}', name: 'apple', category: 'food', keywords: ['fruit', 'red'] },
  { emoji: '\u{1F34F}', name: 'green_apple', category: 'food', keywords: ['fruit'] },
  { emoji: '\u{1F34A}', name: 'orange', category: 'food', keywords: ['fruit', 'citrus'] },
  { emoji: '\u{1F34B}', name: 'lemon', category: 'food', keywords: ['fruit', 'citrus', 'sour'] },
  { emoji: '\u{1F353}', name: 'strawberry', category: 'food', keywords: ['fruit', 'berry'] },
  { emoji: '\u{1F349}', name: 'watermelon', category: 'food', keywords: ['fruit', 'summer'] },
  { emoji: '\u{1F355}', name: 'pizza', category: 'food', keywords: ['food', 'slice'] },
  { emoji: '\u{1F354}', name: 'hamburger', category: 'food', keywords: ['burger', 'food', 'fast'] },
  { emoji: '\u{1F35F}', name: 'fries', category: 'food', keywords: ['chips', 'food', 'fast'] },
  { emoji: '\u{1F32E}', name: 'taco', category: 'food', keywords: ['mexican', 'food'] },
  { emoji: '\u{1F363}', name: 'sushi', category: 'food', keywords: ['japanese', 'fish', 'food'] },
  { emoji: '\u2615', name: 'coffee', category: 'food', keywords: ['drink', 'cafe', 'hot'] },
  { emoji: '\u{1F37A}', name: 'beer', category: 'food', keywords: ['drink', 'alcohol'] },
  { emoji: '\u{1F377}', name: 'wine', category: 'food', keywords: ['drink', 'alcohol', 'glass'] },
  { emoji: '\u{1F370}', name: 'cake', category: 'food', keywords: ['dessert', 'birthday'] },
  { emoji: '\u{1F36B}', name: 'chocolate', category: 'food', keywords: ['candy', 'sweet'] },
  { emoji: '\u{1F369}', name: 'donut', category: 'food', keywords: ['dessert', 'sweet'] },
  { emoji: '\u{1F36A}', name: 'cookie', category: 'food', keywords: ['dessert', 'biscuit'] },
];
